nelmio_api_doc:
    documentation:
        info:
            title: 'Library API'
            description: 'Symfony Library system API documentation'
            version: '1.0.0'
    areas:
        default:
            path_patterns: [ '^/book', '^/api' ]

